/* Auto-generated by tools/convert_assets.py -- do not edit. */
#ifndef PIKA_ATLAS_H
#define PIKA_ATLAS_H

#define ATLAS_TILE_SIZE 512
#define ATLAS_NUM_TILES 2
#define ATLAS_FORMAT GU_PSM_5551

typedef struct {
    int tile;   /* which 512x512 sheet */
    int x, y;   /* top-left pixel in sheet */
    int w, h;   /* size in pixels */
} AtlasFrame;

enum {
    TEX_BALL_BALL_0,
    TEX_BALL_BALL_1,
    TEX_BALL_BALL_2,
    TEX_BALL_BALL_3,
    TEX_BALL_BALL_4,
    TEX_BALL_BALL_HYPER,
    TEX_BALL_BALL_PUNCH,
    TEX_BALL_BALL_TRAIL,
    TEX_MESSAGES_COMMON_GAME_END,
    TEX_MESSAGES_COMMON_READY,
    TEX_MESSAGES_COMMON_SACHISOFT,
    TEX_MESSAGES_JA_FIGHT,
    TEX_MESSAGES_JA_GAME_START,
    TEX_MESSAGES_JA_MARK,
    TEX_MESSAGES_JA_PIKACHU_VOLLEYBALL,
    TEX_MESSAGES_JA_POKEMON,
    TEX_MESSAGES_JA_WITH_COMPUTER,
    TEX_MESSAGES_JA_WITH_FRIEND,
    TEX_MESSAGES_KO_FIGHT,
    TEX_MESSAGES_KO_GAME_START,
    TEX_MESSAGES_KO_MARK,
    TEX_MESSAGES_KO_PIKACHU_VOLLEYBALL,
    TEX_MESSAGES_KO_POKEMON,
    TEX_MESSAGES_KO_WITH_COMPUTER,
    TEX_MESSAGES_KO_WITH_FRIEND,
    TEX_NUMBER_NUMBER_0,
    TEX_NUMBER_NUMBER_1,
    TEX_NUMBER_NUMBER_2,
    TEX_NUMBER_NUMBER_3,
    TEX_NUMBER_NUMBER_4,
    TEX_NUMBER_NUMBER_5,
    TEX_NUMBER_NUMBER_6,
    TEX_NUMBER_NUMBER_7,
    TEX_NUMBER_NUMBER_8,
    TEX_NUMBER_NUMBER_9,
    TEX_OBJECTS_BLACK,
    TEX_OBJECTS_CLOUD,
    TEX_OBJECTS_GROUND_LINE,
    TEX_OBJECTS_GROUND_LINE_LEFTMOST,
    TEX_OBJECTS_GROUND_LINE_RIGHTMOST,
    TEX_OBJECTS_GROUND_RED,
    TEX_OBJECTS_GROUND_YELLOW,
    TEX_OBJECTS_MOUNTAIN,
    TEX_OBJECTS_NET_PILLAR,
    TEX_OBJECTS_NET_PILLAR_TOP,
    TEX_OBJECTS_SHADOW,
    TEX_OBJECTS_SKY_BLUE,
    TEX_OBJECTS_WAVE,
    TEX_PIKACHU_PIKACHU_0_0,
    TEX_PIKACHU_PIKACHU_0_1,
    TEX_PIKACHU_PIKACHU_0_2,
    TEX_PIKACHU_PIKACHU_0_3,
    TEX_PIKACHU_PIKACHU_0_4,
    TEX_PIKACHU_PIKACHU_1_0,
    TEX_PIKACHU_PIKACHU_1_1,
    TEX_PIKACHU_PIKACHU_1_2,
    TEX_PIKACHU_PIKACHU_1_3,
    TEX_PIKACHU_PIKACHU_1_4,
    TEX_PIKACHU_PIKACHU_2_0,
    TEX_PIKACHU_PIKACHU_2_1,
    TEX_PIKACHU_PIKACHU_2_2,
    TEX_PIKACHU_PIKACHU_2_3,
    TEX_PIKACHU_PIKACHU_2_4,
    TEX_PIKACHU_PIKACHU_3_0,
    TEX_PIKACHU_PIKACHU_3_1,
    TEX_PIKACHU_PIKACHU_4_0,
    TEX_PIKACHU_PIKACHU_5_0,
    TEX_PIKACHU_PIKACHU_5_1,
    TEX_PIKACHU_PIKACHU_5_2,
    TEX_PIKACHU_PIKACHU_5_3,
    TEX_PIKACHU_PIKACHU_5_4,
    TEX_PIKACHU_PIKACHU_6_0,
    TEX_PIKACHU_PIKACHU_6_1,
    TEX_PIKACHU_PIKACHU_6_2,
    TEX_PIKACHU_PIKACHU_6_3,
    TEX_PIKACHU_PIKACHU_6_4,
    TEX_SITTING_PIKACHU,
    TEX_COUNT,
};

static const AtlasFrame g_atlas_frames[TEX_COUNT] = {
    [TEX_BALL_BALL_0] = { 0, 0, 471, 40, 40 },  /* ball/ball_0.png */
    [TEX_BALL_BALL_1] = { 0, 40, 471, 40, 40 },  /* ball/ball_1.png */
    [TEX_BALL_BALL_2] = { 0, 80, 471, 40, 40 },  /* ball/ball_2.png */
    [TEX_BALL_BALL_3] = { 0, 120, 471, 40, 40 },  /* ball/ball_3.png */
    [TEX_BALL_BALL_4] = { 0, 160, 471, 40, 40 },  /* ball/ball_4.png */
    [TEX_BALL_BALL_HYPER] = { 0, 200, 471, 40, 40 },  /* ball/ball_hyper.png */
    [TEX_BALL_BALL_PUNCH] = { 0, 240, 471, 40, 40 },  /* ball/ball_punch.png */
    [TEX_BALL_BALL_TRAIL] = { 0, 280, 471, 40, 40 },  /* ball/ball_trail.png */
    [TEX_MESSAGES_COMMON_GAME_END] = { 1, 48, 224, 96, 24 },  /* messages/common/game_end.png */
    [TEX_MESSAGES_COMMON_READY] = { 1, 144, 224, 80, 24 },  /* messages/common/ready.png */
    [TEX_MESSAGES_COMMON_SACHISOFT] = { 1, 0, 256, 360, 20 },  /* messages/common/sachisoft.png */
    [TEX_MESSAGES_JA_FIGHT] = { 0, 0, 0, 160, 160 },  /* messages/ja/fight.png */
    [TEX_MESSAGES_JA_GAME_START] = { 1, 224, 224, 96, 24 },  /* messages/ja/game_start.png */
    [TEX_MESSAGES_JA_MARK] = { 0, 320, 0, 88, 110 },  /* messages/ja/mark.png */
    [TEX_MESSAGES_JA_PIKACHU_VOLLEYBALL] = { 0, 104, 160, 276, 79 },  /* messages/ja/pikachu_volleyball.png */
    [TEX_MESSAGES_JA_POKEMON] = { 1, 192, 128, 200, 32 },  /* messages/ja/pokemon.png */
    [TEX_MESSAGES_JA_WITH_COMPUTER] = { 1, 360, 256, 120, 20 },  /* messages/ja/with_computer.png */
    [TEX_MESSAGES_JA_WITH_FRIEND] = { 1, 0, 276, 120, 20 },  /* messages/ja/with_friend.png */
    [TEX_MESSAGES_KO_FIGHT] = { 0, 160, 0, 160, 160 },  /* messages/ko/fight.png */
    [TEX_MESSAGES_KO_GAME_START] = { 1, 320, 224, 96, 24 },  /* messages/ko/game_start.png */
    [TEX_MESSAGES_KO_MARK] = { 0, 408, 0, 88, 110 },  /* messages/ko/mark.png */
    [TEX_MESSAGES_KO_PIKACHU_VOLLEYBALL] = { 0, 0, 264, 276, 79 },  /* messages/ko/pikachu_volleyball.png */
    [TEX_MESSAGES_KO_POKEMON] = { 1, 0, 192, 200, 32 },  /* messages/ko/pokemon.png */
    [TEX_MESSAGES_KO_WITH_COMPUTER] = { 1, 120, 276, 120, 20 },  /* messages/ko/with_computer.png */
    [TEX_MESSAGES_KO_WITH_FRIEND] = { 1, 240, 276, 120, 20 },  /* messages/ko/with_friend.png */
    [TEX_NUMBER_NUMBER_0] = { 1, 200, 192, 32, 32 },  /* number/number_0.png */
    [TEX_NUMBER_NUMBER_1] = { 1, 232, 192, 32, 32 },  /* number/number_1.png */
    [TEX_NUMBER_NUMBER_2] = { 1, 264, 192, 32, 32 },  /* number/number_2.png */
    [TEX_NUMBER_NUMBER_3] = { 1, 296, 192, 32, 32 },  /* number/number_3.png */
    [TEX_NUMBER_NUMBER_4] = { 1, 328, 192, 32, 32 },  /* number/number_4.png */
    [TEX_NUMBER_NUMBER_5] = { 1, 360, 192, 32, 32 },  /* number/number_5.png */
    [TEX_NUMBER_NUMBER_6] = { 1, 392, 192, 32, 32 },  /* number/number_6.png */
    [TEX_NUMBER_NUMBER_7] = { 1, 424, 192, 32, 32 },  /* number/number_7.png */
    [TEX_NUMBER_NUMBER_8] = { 1, 456, 192, 32, 32 },  /* number/number_8.png */
    [TEX_NUMBER_NUMBER_9] = { 1, 0, 224, 32, 32 },  /* number/number_9.png */
    [TEX_OBJECTS_BLACK] = { 1, 456, 276, 8, 8 },  /* objects/black.png */
    [TEX_OBJECTS_CLOUD] = { 1, 416, 224, 48, 24 },  /* objects/cloud.png */
    [TEX_OBJECTS_GROUND_LINE] = { 1, 360, 276, 16, 16 },  /* objects/ground_line.png */
    [TEX_OBJECTS_GROUND_LINE_LEFTMOST] = { 1, 376, 276, 16, 16 },  /* objects/ground_line_leftmost.png */
    [TEX_OBJECTS_GROUND_LINE_RIGHTMOST] = { 1, 392, 276, 16, 16 },  /* objects/ground_line_rightmost.png */
    [TEX_OBJECTS_GROUND_RED] = { 1, 408, 276, 16, 16 },  /* objects/ground_red.png */
    [TEX_OBJECTS_GROUND_YELLOW] = { 1, 424, 276, 16, 16 },  /* objects/ground_yellow.png */
    [TEX_OBJECTS_MOUNTAIN] = { 0, 0, 343, 432, 64 },  /* objects/mountain.png */
    [TEX_OBJECTS_NET_PILLAR] = { 1, 464, 276, 8, 8 },  /* objects/net_pillar.png */
    [TEX_OBJECTS_NET_PILLAR_TOP] = { 1, 472, 276, 8, 8 },  /* objects/net_pillar_top.png */
    [TEX_OBJECTS_SHADOW] = { 1, 480, 276, 32, 8 },  /* objects/shadow.png */
    [TEX_OBJECTS_SKY_BLUE] = { 1, 440, 276, 16, 16 },  /* objects/sky_blue.png */
    [TEX_OBJECTS_WAVE] = { 1, 32, 224, 16, 32 },  /* objects/wave.png */
    [TEX_PIKACHU_PIKACHU_0_0] = { 0, 432, 343, 64, 64 },  /* pikachu/pikachu_0_0.png */
    [TEX_PIKACHU_PIKACHU_0_1] = { 0, 0, 407, 64, 64 },  /* pikachu/pikachu_0_1.png */
    [TEX_PIKACHU_PIKACHU_0_2] = { 0, 64, 407, 64, 64 },  /* pikachu/pikachu_0_2.png */
    [TEX_PIKACHU_PIKACHU_0_3] = { 0, 128, 407, 64, 64 },  /* pikachu/pikachu_0_3.png */
    [TEX_PIKACHU_PIKACHU_0_4] = { 0, 192, 407, 64, 64 },  /* pikachu/pikachu_0_4.png */
    [TEX_PIKACHU_PIKACHU_1_0] = { 0, 256, 407, 64, 64 },  /* pikachu/pikachu_1_0.png */
    [TEX_PIKACHU_PIKACHU_1_1] = { 0, 320, 407, 64, 64 },  /* pikachu/pikachu_1_1.png */
    [TEX_PIKACHU_PIKACHU_1_2] = { 0, 384, 407, 64, 64 },  /* pikachu/pikachu_1_2.png */
    [TEX_PIKACHU_PIKACHU_1_3] = { 0, 448, 407, 64, 64 },  /* pikachu/pikachu_1_3.png */
    [TEX_PIKACHU_PIKACHU_1_4] = { 1, 0, 0, 64, 64 },  /* pikachu/pikachu_1_4.png */
    [TEX_PIKACHU_PIKACHU_2_0] = { 1, 64, 0, 64, 64 },  /* pikachu/pikachu_2_0.png */
    [TEX_PIKACHU_PIKACHU_2_1] = { 1, 128, 0, 64, 64 },  /* pikachu/pikachu_2_1.png */
    [TEX_PIKACHU_PIKACHU_2_2] = { 1, 192, 0, 64, 64 },  /* pikachu/pikachu_2_2.png */
    [TEX_PIKACHU_PIKACHU_2_3] = { 1, 256, 0, 64, 64 },  /* pikachu/pikachu_2_3.png */
    [TEX_PIKACHU_PIKACHU_2_4] = { 1, 320, 0, 64, 64 },  /* pikachu/pikachu_2_4.png */
    [TEX_PIKACHU_PIKACHU_3_0] = { 1, 384, 0, 64, 64 },  /* pikachu/pikachu_3_0.png */
    [TEX_PIKACHU_PIKACHU_3_1] = { 1, 448, 0, 64, 64 },  /* pikachu/pikachu_3_1.png */
    [TEX_PIKACHU_PIKACHU_4_0] = { 1, 0, 64, 64, 64 },  /* pikachu/pikachu_4_0.png */
    [TEX_PIKACHU_PIKACHU_5_0] = { 1, 64, 64, 64, 64 },  /* pikachu/pikachu_5_0.png */
    [TEX_PIKACHU_PIKACHU_5_1] = { 1, 128, 64, 64, 64 },  /* pikachu/pikachu_5_1.png */
    [TEX_PIKACHU_PIKACHU_5_2] = { 1, 192, 64, 64, 64 },  /* pikachu/pikachu_5_2.png */
    [TEX_PIKACHU_PIKACHU_5_3] = { 1, 256, 64, 64, 64 },  /* pikachu/pikachu_5_3.png */
    [TEX_PIKACHU_PIKACHU_5_4] = { 1, 320, 64, 64, 64 },  /* pikachu/pikachu_5_4.png */
    [TEX_PIKACHU_PIKACHU_6_0] = { 1, 384, 64, 64, 64 },  /* pikachu/pikachu_6_0.png */
    [TEX_PIKACHU_PIKACHU_6_1] = { 1, 448, 64, 64, 64 },  /* pikachu/pikachu_6_1.png */
    [TEX_PIKACHU_PIKACHU_6_2] = { 1, 0, 128, 64, 64 },  /* pikachu/pikachu_6_2.png */
    [TEX_PIKACHU_PIKACHU_6_3] = { 1, 64, 128, 64, 64 },  /* pikachu/pikachu_6_3.png */
    [TEX_PIKACHU_PIKACHU_6_4] = { 1, 128, 128, 64, 64 },  /* pikachu/pikachu_6_4.png */
    [TEX_SITTING_PIKACHU] = { 0, 0, 160, 104, 104 },  /* sitting_pikachu.png */
};

#endif /* PIKA_ATLAS_H */
