/* Auto-generated by tools/convert_assets.py -- do not edit. */
#ifndef PIKA_AUDIO_LAYOUT_H
#define PIKA_AUDIO_LAYOUT_H

enum {
    SFX_PIPIKACHU = 0,
    SFX_PIKA = 1,
    SFX_CHU = 2,
    SFX_PI = 3,
    SFX_PIKACHU = 4,
    SFX_POWERHIT = 5,
    SFX_BALLTOUCHESGROUND = 6,
    SFX_COUNT,
};

typedef struct { unsigned int offset; unsigned int nsamples; } SfxInfo;
static const SfxInfo g_sfx_info[SFX_COUNT] = {
    { 64, 55384 },  /* pipikachu */
    { 110832, 23556 },  /* pika */
    { 157944, 21156 },  /* chu */
    { 200256, 10196 },  /* pi */
    { 220648, 40846 },  /* pikachu */
    { 302340, 13768 },  /* powerhit */
    { 329876, 16218 },  /* balltouchesground */
};

/* BGM total sample count (mono 16-bit 44100) - patched below. */
#define BGM_TOTAL_SAMPLES 3674112

#endif /* PIKA_AUDIO_LAYOUT_H */
